@host = https://localhost:7041
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlci5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IlRpZmZhbnkiLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6IjQwZGM2MGY1LTMwYzYtNGZmNi1hOTU2LTI0OGY1YTdkMDQwZCIsImV4cCI6MTc0NzM1OTU2OSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.wEcm5CD0jxPvnYRHtdPCLKDsN6obVzXdOHpXEv6cHk8

GET {{host}}/dinners
Authorization: Bearer {{token}}