@host = https://localhost:7041

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNTg1NDBhMy05MmU2LTRlZWQtYjI5ZS0wZDVjMGFmMjE0YzUiLCJnaXZlbl9uYW1lIjoiQ2VzYXIiLCJmYW1pbHlfbmFtZSI6Ik1hdHN1YmF5YXNoaSIsImp0aSI6IjlmNGE1NzZjLTk2NGQtNDNjNC1iYTMxLWJlMTNkYjAyMmQ0ZSIsImV4cCI6MTc0MzgyNDgyNiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.bQ5YWtSkml0bE0FNAS3qZBixQDa_FnPSCUYizZRMr14