@host = https://localhost:7041
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlci5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6IlRpZmZhbnkiLCJmYW1pbHlfbmFtZSI6IkRvZSIsImp0aSI6ImQxN2YzNjY2LTgxYjUtNGQ4Mi1hMTQwLTExYzU0MWI5Y2VjMCIsImV4cCI6MTc0ODA1NzYzMiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.VTa7nD8Iovl7uYlplCxFAmcOuW1vRTHLpjgVm4luaBk
@billId = c75fefdd-575c-4ef6-8c7d-092465036b84

GET {{host}}/bills/{{billId}}
Content-Type: application/json
Authorization: Bearer {{token}}
